/// Flutter icons PoolishIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PoolishIcons
///      fonts:
///       - asset: fonts/PoolishIcons.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class PoolishIcons {
  PoolishIcons._();

  static const _kFontFam = 'PoolishIcons';

  static const IconData setting = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData history = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData test = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData history_1 = IconData(0xe863, fontFamily: _kFontFam);
}
